//go:build !wasm

package crudview

import (
	. "github.com/tinywasm/css"
)

func GenerateCSS() *Stylesheet {
	s := NewStylesheet(
		Rule(clsModuleContent,
			Display(Grid),
			Border(Str(".1vw solid var(--color-outline-variant)")),
			BorderRadius(Str("0 .4em .4em 0")),
			RawRule("grid-template: none / auto 1fr"),
		),

		Rule(clsArticleContend,
			Flex(None),
			Display(Grid),
			RawRule("grid-template: 'title' var(--cv-title-height, 8vh) 'article' 80vh 'controls' var(--cv-controls-height, 9vh) / 66vw"),
		),

		Rule(clsArticleContendFullPage,
			Display(Grid),
			RawRule("grid-template: 'title' var(--cv-title-height, 8vh) 'article' 89vh / 96vw"),
		),

		Rule(clsAsideContend,
			Flex(None),
			MarginLeft(Str("var(--cv-mag-pri, .5rem)")),
			Display(Grid),
			RawRule("grid-template: 'aside-list' var(--cv-title-height, 8vh) 'aside-list' 80vh 'aside-search' var(--cv-controls-height, 9vh) / 29vw"),
		),

		Rule(clsTitleContainer,
			GridArea(Str("title")),
			Display(Flex_),
			AlignItems(Center),
			Background(Str("var(--color-primary)")),
		),

		Rule("."+string(clsTitle)+" h1",
			MarginLeft(Str(".7em")),
			Color(Str("var(--color-on-primary)")),
			FontSize(Str("1.5rem")),
		),

		Rule("article",
			GridArea(Str("article")),
			Background(Str("var(--color-surface)")),
			BorderRadius(Str(".4em .4em 0 0")),
			Display(Flex_),
			FlexDirection(Column),
			MarginLeft(Str("var(--cv-mag-cua, .2rem)")),
		),

		Rule(clsBoxContent,
			FlexGrow(Str("1")),
			Display(Flex_),
			MinHeight(Str("0")),
			Background(Str("var(--color-surface-variant)")),
			BorderRadius(Str(".4em")),
			Padding(Str("var(--cv-mag-pri, .5rem) 0 var(--cv-mag-pri, .5rem) var(--cv-mag-pri, .5rem)")),
		),

		Rule(clsControls,
			GridArea(Str("controls")),
			MarginBottom(Str("var(--cv-mag-pri, .5rem)")),
		),

		Rule(clsContebuton,
			Display(Flex_),
			Height(Str("100%")),
			Background(Str("var(--color-surface)")),
			JustifyContent(Str("space-between")),
			Padding(Str(".1em")),
			BorderRadius(Str("0 0 .4em .4em")),
		),

		Rule(clsBtnCrud,
			Flex(Auto),
			Margin(Str(".25em")),
			Padding(Str(".4rem")),
			Background(Str("var(--color-primary)")),
			Color(Str("var(--color-on-primary)")),
			BorderRadius(Str(".4em")),
			Border(Str("none")),
			Cursor(Pointer),
			Display(Flex_),
			AlignItems(Center),
			JustifyContent(Center),
		),

		Rule("."+string(clsBtnCrud)+":disabled",
			Background(Str("var(--color-outline-variant)")),
			Color(Str("var(--color-on-surface-variant)")),
			Cursor(Str("not-allowed")),
			Opacity(0.6),
		),

		Rule(clsAsideList,
			GridArea(Str("aside-list")),
			MarginTop(Str("var(--cv-mag-pri, .5rem)")),
			Background(Str("var(--color-surface)")),
			BorderRadius(Str(".4em .4em 0 0")),
			Display(Flex_),
			FlexDirection(Column),
			PaddingTop(Str("var(--cv-mag-sec, .2rem)")),
		),

		Rule(clsListaBox,
			Display(Flex_),
			Height(Str("100%")),
			FlexDirection(Column),
			Background(Str("var(--color-surface-variant)")),
			BorderRadius(Str(".4em")),
			Padding(Str(".2rem")),
			Overflow(Hidden),
		),

		Rule(clsLista,
			FlexGrow(Str("1")),
			Overflow(Auto),
			MinHeight(Str("0")),
			Padding(Str(".2em")),
			ListStyle(None),
		),

		Rule(clsTargetLi,
			Position(Relative),
			Display(Flex_),
			AlignItems(Center),
			MinHeight(Str("60px")),
			MaxHeight(Str("60px")),
			Width(Str("100%")),
			Padding(Str(".3em")),
			MarginBottom(Str("1.2em")),
			Cursor(Pointer),
			Border(Str("2px solid var(--color-outline-variant)")),
			BorderRadius(Str(".3em")),
			Background(Str("var(--color-surface)")),
			Transition(Str(".3s all ease")),
		),

		Rule(clsTargetLiOn,
			BorderColor(Str("var(--color-primary)")),
			Background(Str("var(--color-primary-container)")),
		),

		Rule(clsDescriptionTarget,
			Position(Absolute),
			Right(Px(5)),
			Bottom(Px(-10)),
			Background(Str("var(--color-secondary-container)")),
			Color(Str("var(--color-on-secondary-container)")),
			FontSize(Pct(80)),
			BorderRadius(Str(".4em")),
			Padding(Str(".3em")),
		),

		Rule(clsAsideSearch,
			GridArea(Str("aside-search")),
			Display(Flex_),
			Background(Str("var(--color-surface)")),
			Padding(Str(".1em")),
			BorderRadius(Str("0 0 .4em .4em")),
			MarginBottom(Str("var(--cv-mag-pri, .5rem)")),
			AlignItems(Center),
		),

		Rule("."+string(clsAsideSearch)+" label",
			Background(Str("var(--color-primary)")),
			Color(Str("var(--color-on-primary)")),
			Padding(Str(".3em")),
			BorderRadius(Str(".3em 0 0 .3em")),
			Display(Flex_),
		),

		Rule("."+string(clsAsideSearch)+" input",
			FlexGrow(Str("1")),
			Border(Str("1px solid var(--color-outline-variant)")),
			Padding(Str(".3em")),
			BorderRadius(Str("0 .3em .3em 0")),
		),

		Rule(clsIcon16,
			Width(Px(16)),
			Height(Px(16)),
			Decl{Prop: "fill", Val: "currentColor"},
		),
	)

	return s
}
