//go:build !wasm

package platformd

import (
	. "github.com/tinywasm/css"
)

// RenderCSS implements CSSProvider.
func (p *Platform) RenderCSS() *Stylesheet {
	return NewStylesheet(
		Root(
			Declare(tokenFontSizeNormal, "1.1rem"),
			Declare(tokenFontSizeSmall, ".6rem"),
			Declare(tokenColorPrimary, "#ffffff"),
			Declare(tokenColorSecondary, "#3f88bf"),
			Declare(tokenColorTertiary, "#c2c1c1"),
			Declare(tokenColorQuaternary, "#000000"),
			Declare(tokenColorGray, "#e9e9e9"),
			Declare(tokenColorSelection, "#ff9300"),
			Declare(tokenColorHover, "#ff95008e"),
			Declare(tokenColorSuccess, "#aadaff7c"),
			Declare(tokenColorError, "#f20707"),
			Declare(tokenMenuSize, "6vh"),
			Declare(tokenHeaderHeight, "5vh"),
			Declare(tokenContentHeight, "94vh"),
			Declare(tokenContentWidth, "100vw"),
			Declare(tokenSlideDur, "0.6s"),
			Declare(tokenTransitionWait, "0s"),
		),

		// Universal reset for platform elements
		Rule(Selector("."+string(clsRoot)+" *"),
			RawRule("-webkit-box-sizing: border-box;"),
			RawRule("-moz-box-sizing: border-box;"),
			Margin(Zero),
			Padding(Zero),
			BoxSizing(Str("border-box")),
			Outline(None),
			TextDecoration(None),
			ListStyle(None),
			ListStyleType(None),
			RawRule("-webkit-user-select: none;"),
			RawRule("-khtml-user-select: none;"),
			RawRule("-moz-user-select: none;"),
			RawRule("-ms-user-select: none;"),
			UserSelect(None),
			FontFamily(Str("Arvo")),
		),

		/************ MOBILE (Default) ************/

		Rule(clsRoot,
			FontSize(Rem(0.8)),
			Background(tokenColorTertiary),
			Width(Vw(100)),
			Height(Vh(100)),
			Position(Str("relative")),
			Overflow(Hidden),
		),

		Rule(clsHeader,
			Position(Fixed),
			AlignSelf(FlexEnd),
			Bottom(Px(5)),
			MarginLeft(Px(5)),
			ZIndex(Str("5")),
		),

		Rule(Selector("."+string(clsRoot)+" a:link"), Color(tokenColorQuaternary)),
		Rule(Selector("."+string(clsRoot)+" a:visited"), Color(tokenColorQuaternary)),

		// Hamburger button — visible only on mobile
		Rule(clsHamburger,
			Position(Fixed),
			Top(Px(8)),
			Right(Px(8)),
			ZIndex(Str("10")),
			Width(Px(44)),
			Height(Px(44)),
			Background(tokenColorSecondary),
			BorderRadius(Px(6)),
			Display(Flex_),
			FlexDirection(Column),
			AlignItems(Center),
			JustifyContent(SpaceAround),
			Padding(Px(10), Px(8)),
			Cursor(Pointer),
			Border(Str("none")),
		),

		Rule(Selector("."+string(clsHamburger)+" span"),
			Display(Block),
			Width(Pct(100)),
			Height(Px(2)),
			Background(tokenColorPrimary),
			BorderRadius(Px(2)),
		),

		// Nav drawer — hidden off-screen right using transform (no reflow, GPU)
		Rule(clsMenu,
			Background(tokenColorGray),
			Position(Fixed),
			Top(Zero),
			Right(Zero),
			Width(Vw(75)),
			Height(Vh(100)),
			ZIndex(Str("9")),
			Transform(Str("translateX(100%)")),
		),

		// Nav overlay backdrop
		Rule(clsNavOverlay,
			Position(Fixed),
			Top(Zero),
			Left(Zero),
			Width(Pct(100)),
			Height(Pct(100)),
			Background(Str("rgba(0,0,0,0.45)")),
			ZIndex(Str("8")),
			Display(None),
		),

		// Open state — keyframe animation so it fires on new DOM elements too
		Rule(Selector("."+string(clsMenuOpen)+" ."+string(clsMenu)),
			Transform(Str("translateX(0)")),
			Animation(Str("pdDrawerOpen"), tokenSlideDur, Str("ease")),
		),
		Rule(Selector("."+string(clsMenuOpen)+" ."+string(clsNavOverlay)),
			Display(Block),
		),

		Rule(clsNavbar,
			Display(Flex_),
			FlexDirection(Column),
			AlignItems(Str("stretch")),
			JustifyContent(SpaceAround),
			Height(Pct(100)),
		),

		Rule(clsNavItem,
			Width(Pct(100)),
			Flex(Str("1")),
		),

		Rule(clsNavActive,
			Background(tokenColorSelection),
		),

		Rule(Selector("."+string(clsNavActive)+", ."+string(clsNavActive)+" > svg"),
			Color(tokenColorPrimary),
			Transition(Str("0.3s"), Str("all"), Str("ease")),
		),

		Rule(clsNavLink,
			Display(Flex_),
			FlexDirection(Row),
			AlignItems(Center),
			Height(Pct(100)),
			Padding(Zero, Rem(1)),
			Transition(tokenSlideDur, Str("all"), Str("ease")),
		),

		Rule(ClsNavIcon,
			Color(tokenColorSecondary),
			Height(Em(2.5)),
			Width(Em(2.5)),
			MinWidth(Em(2.5)),
			Transition(tokenSlideDur, Str("all"), Str("ease")),
			MarginRight(Rem(0.8)),
		),

		Rule(clsLinkText,
			Color(tokenColorSecondary),
			FontSize(Em(1.1)),
		),

		Rule(clsPanel,
			Display(None),
		),

		Rule(clsPanelActive,
			Display(Block),
			Top(Zero),
			Left(Zero),
			Margin(Zero),
			ZIndex(Str("1")),
			Width(tokenContentWidth),
			Height(Vh(100)),
			Position(Absolute),
			Background(tokenColorSecondary),
			Animation(Str("pdSlideInTop"), tokenSlideDur, Str("ease-in-out")),
		),

		Rule(clsMsgDesktop,
			Width(Pct(100)),
			JustifyContent(Center),
			Display(Flex_),
			AlignItems(Center),
		),

		Rule(clsArea,
			TextTransform(Uppercase),
			Color(tokenColorPrimary),
			TextAlign(Center),
			Display(Flex_),
			AlignItems(Center),
		),

		Rule(clsUserBlock,
			Display(Flex_),
			AlignItems(Center),
		),

		Rule(clsOrientationWarn,
			ZIndex(Str("4")),
			Position(Fixed),
			Top(Zero),
			Left(Zero),
			Width(Pct(100)),
			Height(Pct(100)),
			JustifyContent(Center),
			AlignItems(Center),
			Display(None),
			Color(tokenColorPrimary),
			TouchAction(None),
			Background(tokenColorSecondary),
		),

		Rule(clsMsgMobile,
			ZIndex(Str("4")),
			Position(Fixed),
			Top(Zero),
			Left(Zero),
			Width(Pct(100)),
			Height(Pct(100)),
			JustifyContent(Center),
			AlignItems(Center),
			Display(Flex_),
			Background(Str("rgba(255, 255, 255, 0.8)")),
			Visibility(Visible),
		),

		Rule(clsMsg,
			TextAlign(Center),
			Padding(Px(20)),
			Width(Pct(80)),
			FontSize(Em(1.3)),
			TextShadow(Em(0.1), Em(0.1), Em(0.1), Hex("#ffffff")),
			Animation(Str("pdFadeIn"), tokenTransitionWait),
		),

		// Message variants
		Rule(Selector(".pd-msg-info"), Color(tokenColorTertiary)),
		Rule(Selector(".pd-msg-error"), Color(tokenColorError)),
		Rule(Selector(".pd-msg-success"), Color(tokenColorSecondary)),
		Rule(Selector(".pd-msg-warning"), Color(tokenColorSelection)),

		Keyframes("pdFadeOut",
			At("from", Opacity(1.0), Visibility(Visible)),
			At("to", Opacity(0.7), Visibility(Hidden)),
		),

		Keyframes("pdFadeIn",
			At("from", Opacity(0.0), Visibility(Hidden)),
			At("to", Opacity(1.0), Visibility(Visible)),
		),

		Keyframes("pdSlideInTop",
			At("from", Top(Vh(-100))),
			At("to", Top(Zero)),
		),

		Keyframes("pdSlideInLeft",
			At("from", Left(Pct(-100))),
			At("to", Left(Zero)),
		),

		Keyframes("pdDrawerOpen",
			At("from", Transform(Str("translateX(100%)"))),
			At("to", Transform(Str("translateX(0)"))),
		),

		/************ DESKTOP ************/
		MediaDesktop(
			Root(
				Declare(tokenHeaderHeight, "5vh"),
				Declare(tokenContentHeight, "95vh"),
				Declare(tokenMenuSize, "5vw"),
				Declare(tokenContentWidth, "95vw"),
			),

			Rule(clsRoot,
				Overflow(Hidden),
				Background(tokenColorGray),
				FontSize(Px(16)),
				Height(Vh(100)),
				// Reset mobile flex centering — critical so grid items stretch to full height
				AlignItems(Str("normal")),
				JustifyContent(Str("normal")),
				Display(Grid),
				GridTemplate(Str(`"header         header" `+tokenHeaderHeight.Var()+`
					"module-content menu-container" `+tokenContentHeight.Var()+` /
					`+tokenContentWidth.Var()+` `+tokenMenuSize.Var())),
			),

			// Hide hamburger and overlay on desktop
			Rule(clsHamburger, Display(None)),
			Rule(clsNavOverlay, Display(None)),

			Rule(clsHeader,
				AlignSelf(Unset),
				Bottom(Auto),
				Position(Unset),
				MarginLeft(Zero),
				MaxHeight(tokenHeaderHeight),
				Width(Vw(100)),
				GridArea(Str("header")),
				Display(Grid),
				GridTemplateColumns(Str("1fr 3fr 1fr")),
				Background(tokenColorGray),
			),

			Rule(clsMenu,
				Position(Fixed),
				GridArea(Str("menu-container")),
				Top(tokenHeaderHeight),
				Right(Zero),
				Width(tokenMenuSize),
				Height(tokenContentHeight),
				MarginLeft(Auto),
				Background(tokenColorGray),
				Transform(Str("none")),
				Animation(Str("none")),
				Transition(Str("0.3s"), Str("width"), Str("ease")),
			),

			Rule(clsMenu.Hover(),
				Width(Em(10)),
			),

			Rule(Selector("."+string(clsMenu)+":hover ."+string(clsLinkText)),
				Display(Block),
			),

			Rule(clsNavbar,
				FlexDirection(Column),
				JustifyContent(SpaceAround),
				AlignItems(Str("stretch")),
			),

			// Each nav item takes equal share of the rail height — larger hit targets
			Rule(clsNavItem,
				Height(Auto),
				Flex(Str("1")),
			),

			Rule(clsNavLink,
				FlexDirection(Row),
				JustifyContent(Unset),
				Height(Pct(100)),
				Padding(Zero, Em(0.5)),
			),

			Rule(Selector("."+string(clsNavLink)+":hover"),
				Background(tokenColorHover),
			),

			Rule(Selector("."+string(clsNavActive)+", ."+string(clsNavActive)+" > ."+string(clsLinkText)),
				Color(tokenColorPrimary),
			),

			Rule(clsLinkText,
				Color(tokenColorSecondary),
				Display(None),
			),

			Rule(ClsNavIcon,
				MaxWidth(Em(2.5)),
				MinWidth(Em(2.5)),
				MarginRight(Zero),
			),

			Rule(clsStage,
				GridArea(Str("module-content")),
				Position(Str("relative")),
				Height(Pct(100)),
				Overflow(Hidden),
			),

			Rule(clsPanel,
				Display(None),
			),

			Rule(clsPanelActive,
				Display(Block),
				Position(Absolute),
				Top(Zero),
				Left(Zero),
				Width(Pct(100)),
				Height(Pct(100)),
				BorderRadius(Str("0 .4em 0 0")),
				Animation(Str("pdSlideInLeft"), tokenSlideDur, Str("ease-in-out")),
			),

			Rule(clsMsg,
				Padding(Zero),
				Animation(Str("pdFadeIn"), tokenTransitionWait),
				Visibility(Visible),
				Width(Pct(100)),
			),

			Rule(clsUserBlock,
				FontSize(Calc(".5em + .5vh")),
				MarginLeft(Rem(0.4)),
			),

			Rule(clsArea,
				FontSize(Calc(".5em + .5vh")),
				MarginLeft(Auto),
				MarginRight(Rem(0.4)),
				TextAlign(RightText),
			),

			Rule(clsMsgDesktop,
				FontSize(Calc(".4em + .4vh")),
			),

			Rule(clsMsgMobile,
				All(Initial),
				Display(None),
			),
		),

		Media("(orientation: portrait)",
			Rule(clsOrientationWarn, Display(None)),
		),

		Media("(orientation: landscape) and (min-width: 600px) and (max-width: 1024px)",
			Rule(clsOrientationWarn, Display(Flex_)),
		),

		Rule(Selector("."+string(clsOrientationWarn)+":empty"),
			Display(None),
		),

		// Hide msg-mobile when empty (no notifications) — prevents blank overlay blocking content
		Rule(Selector("."+string(clsMsgMobile)+":empty"),
			Display(None),
		),
	)
}
